### ISSUE TITLE
Define rule DDF99982: Among the Objectives for a StudyDesign is exactly one with a level code of "Primary"

### ISSUE THREAD

**Issue by DianeWold** [cdisc-org/ddf-core-poc#111]
CHK0035: I.e., a study design has one, and only one, primary objective.

**Comment by DianeWold** [comment]
Created DDF99982 in the rule editor.

**Comment by ASL-rmarshall** [comment]
Moved text from `Plain Language Expression` to the beginning of `Description` and removed `Criteria` from the reference because most attributes are blank (and can't be removed individually).  Added value for `Origin` and `Rule Identifier` / `Version`. Tweaked the `Description` text to say "None*, or more than one,* of the Objectives..." because the check is for "not exactly one".

Review complete.
