### ISSUE TITLE
Define rule DDF99990: A relationship cannot exist between an instance of a class and itself

### ISSUE THREAD

**Issue by DianeWold** [cdisc-org/ddf-core-poc#115]
CHK0052: I.e. In a relationship between two instances of a class, the two instances of the class cannot have the same id.

**Comment by drewcdisc** [comment]
We can build this with a limited set of rules based on the few instances of relationships

**Comment by ASL-rmarshall** [comment]
A separate rule will be created for each cyclical relationship type where only a single target may be specified:
- `previous`
- `next`
- `defaultCondition`

These rules will be specified in the form "If the [`previousId`|`nextId`|`defaultConditionId`] column is present and populated, its value cannot be the same as the value of the `id` column".

There will also be a separate single rule covering any cyclical relationship types where there may be more than one target (currently only one type defined in the model):
- `children`

This rule will rely on the representation of the multiple referenced `id` values in the "Multiple_Values" dataset and will be in the form "If value of the `parent_attr` column is 'childrenIds', the value of the `value` column cannot be the same as the value of the `parent_id` column". (Note that `childrenIds` will be renamed to `childIds` in a later version of USDM - see )

**Comment by ASL-rmarshall** [comment]
Removed Criteria section from Authorities / Standards / References because most sub-attributes were blank (and the editor won't let them be removed individually.  Moved the plain language description of the rule into the description. Otherwise, review completed successfully. 

Also reworded the description and output message when splitting into separate rules:
- DDF00021: check that the `id` value is not the same as `previousId`, `nextId` and `defaultConditionId` (when specified).
- DDF00022: check that the `id` value is not the same as an value in `childrenIds` (when specified).
