### ISSUE TITLE
Define rule DDF99977: For a Timing from an anchor (with type "fixed reference), relativeToFrom is "start to start"

### ISSUE THREAD

**Issue by DianeWold** [cdisc-org/ddf-core-poc#119]
CHK0029: A timing relative to an anchor should have a value of relative to from either "start to start" to "end to start".  I.e., the "leg" of a timing that links to an anchor has to link to the start of an anchor.  This assumes that the anchor is at the "from" end of the relationship, and that an anchor has only a start (or that start and end are the same)
Also assumes (an assumption that needs to be checked) that in a to-from relationship

- from is the established instance (e.g., the anchor)
- to is the instance being added to the timeline

From Berber's document "USDM Check categories v2" : -	In case relativeToFrom=“fixed reference” the timing.type should be “Start to Start” (to be checked with Dave, based on his example)

So this define rule can't be advanced until after consultation with Dave I-H.

**Comment by ASL-rmarshall** [comment]
I agree that it would be best to check with Dave about this. The important thing is to be able to identify whether it's the start or the end of the "from" activity that defines the anchor (e.g., does the clock start ticking when dosing starts or when it ends?). At the moment, the codelist for `relativeToFrom` only contains two-part codes:
|Concept C-code|Preferred Term|CDISC Definition|
|-----|-----|-----|
|C201352|End to End|A timing relationship defined as the end of one event to the end of another event.|
|C201353|End to Start|A timing relationship defined as the end of one event to the start of another event.|
|C201354|Start to End|A timing relationship defined as the start of one event to the end of another event.|
|C201355|Start to Start|A timing relationship defined as the start of one event to the start of another event.|

(Note: given that all codes are defined as "from" something "to" something, it might be better to rename the attribute as `relativeFromTo`)

Given that it's only the first part of the (de)code (the "from" part) that's relevant, there seem to be two options (if we want to ensure that `relativeToFrom` is specified consistently for anchors):
1. Choose which of the two available codes should be used to indicate "Start" vs "End" (I'd prefer using "Start to Start" and "End to End" because you get the intended value if you look at either the first or second part of the decode).
2. Add two new codes for just "Start" and "End" to the codelist for `relativeToFrom` to be used specifically for anchors.

In either case, the rule would then check that only appropriate codes are used for anchors. If the second option were chosen, the rule would also check that the new anchor-specific codes are not used for non-anchors.

**Comment by DianeWold** [comment]
Removed "end to start" from rule.

**Comment by ASL-rmarshall** [comment]
Rule ID was changed from DDF99977 to DDF00036.

**Comment by ASL-rmarshall** [comment]
Review complete as part of review of #155
