### ISSUE TITLE
Define rule DDF00015: Study must have a study phase from the controlled terminology list.

### ISSUE THREAD

**Issue by nickdedonder** [cdisc-org/ddf-core-poc#17]
CHK0026: CDISC Study Phase codes used

**Comment by DianeWold** [comment]
The terminology is from CDISC CT, which is slightly different from the terminology in M11, e.g., "PHASE I TRIAL" rather than "Phase 1".  The terminology includes only terms from the CDISC Codelist that correspond to the M11 list, although there are more terms in the CDISC codelist.
The Validator Rule Message is "Protocol Full Title Required", but I think it should be, "Trial Phase Required".

**Comment by ASL-rmarshall** [comment]
If/when we convert this rule to reference controlled terminology, it will be complicated by the use of `AliasCode`, which has one associated `StandardCode` (defined using the `Code` entity) and may have 1 or more associated `StandardCodeAliases` (also defined using the `Code` entity). I'm not 100% sure how alias codes work, but it may be that the check should be "does not have an standard code alias in the specified list".

**Comment by DianeWold** [comment]
@rbakercdisc1 The parts needed to move to done are there. However, the Validator Rule Message is "Protocol Full Title Required", but I think it should be, "Trial Phase Required".

**Comment by rbakercdisc1** [comment]
@DianeWold  Updated.

**Comment by nickdedonder** [comment]
We agreed that it's only the standard code that needs to be checked for conformance
