### ISSUE TITLE
Create rule DDF00004: Study Protocol Document Scientific Title Required

### ISSUE THREAD

**Issue by nickdedonder** [cdisc-org/ddf-core-poc#26]
Create rule defined for #6

**Comment by ASL-rmarshall** [comment]
This rule could be created as a straightforward check to make sure the `scientificTitle` is not empty in the `StudyProtocolDocumentVersion` entity. However, we decided not to progress with creation/finalization of this rule in the rule editor because checking for population of the `scientificTitle` attribute would be performed by the generic cardinality-based rule (#24).
