### ISSUE TITLE
Define rule DDF00006: Timing windows must be fully defined

### ISSUE THREAD

**Issue by nickdedonder** [cdisc-org/ddf-core-poc#8]
CHK0017: Guidance in section 1.3 of both the M11 Template (p22) and Tech Spec (p114) says (with bolding brackets round "trial" added by me - the Template text says "participants" instead of "trial participants" doesn't appear there in the Template text):
>The schedule of activities must capture the procedures that will be accomplished at each trial visit, and all contact with [trial] participants, for example, telephone contacts. This includes any tests that are used for eligibility, participant randomisation or stratification, or decisions on trial intervention discontinuation. **Allowable windows should be stated for all visits**.

Based on this, there should be 3 rules:
1. Every visit must have associated timing (#52).
2. Every visit timing must have a window (#53).
3. Timing windows must be fully defined (#28 )

**Comment by gerrycampion** [comment]
I think this check would be supported by the engine, but the current check logic in the rule needs some work

**Comment by ASL-rmarshall** [comment]
@rbakercdisc1 The description of this check is "Protocol trial schema with timing windows must have lower timing window and upper timing window."  Looking at the Cited Guidance in the check definition, I think it's important that the text shown in the "Cited Guidance" of the check specification matches what's found in the specified place in the cited document(s). I also wonder if either the check needs to be more complicated or split into several checks:
- Guidance in section 1.3 of both the M11 Template (p22) and Tech Spec (p114) says (with bolding brackets round "trial" added by me - the Template text says "participants" instead of "trial participants" doesn't appear there in the Template text):
    >The schedule of activities must capture the procedures that will be accomplished at each trial visit, and all contact with [trial] participants, for example, telephone contacts. This includes any tests that are used for eligibility, participant randomisation or stratification, or decisions on trial intervention discontinuation. **Allowable windows should be stated for all visits**.
    - This seems to indicate that there should be a check to ensure that a timing window is defined for every visit - i.e., every instance of the `Encounter` class should have the `id` value of an existing instance of the `Timing` class specified in `encounterScheduledAtTiming`.  I don't see this in any of the existing JSON test data, where `encounterScheduledAtTiming` is always `null`.
    - I agree "windows should be stated" indicates that both `timingWindowLower` and `timingWindowUpper` should have a value, but this would only be true for instances of the `Timing` class that are reference as `encounterScheduledAtTiming` from an `Encounter` (it's possible for a study to contain defined timings that are not visit timings, and the rule about windowing would not apply to these).
- I assume the references to section "5.0" for both the Template (p29) and Tech Spec (p154) is meant to be "5." as there is no "5.0". However, the guidance on these pages relates to trial population, not visit windows.
-  The guidance in section 5.6 of the Template (p30) and Tech Spec (p169) does mention time windows, but this is time window for repeating procedures after screen failure, not time windows for visits.
- The guidance on page 261 of the Tech Spec relates to Pharmacokinetics. There is a mention of sampling time relative to ingestion of food, but this is not a visit window.

**Comment by rbakercdisc1** [comment]
@ASL-rmarshall  
We debated this in terms of how the timing should be differentiated in the logic. I am not sure of the answer.

In terms of the resource, I was trying to provide any reference found in M11 which as you state is not much. I felt compelled to show due diligence and point out what was included. Perhaps, it may be better to only show it if it is perfectly aligned and supported. 

I agree with your statements. Do you have recommendations for the logic (include the encounterSheduleTiming)?  There is an additional rule for the Timeline and ScheduledInstances.

**Comment by DianeWold** [comment]
The UML seems to indicate that the attributes timingWindow, timingWindowLower, and timingWindowUpper are optional.  I would interpret the statement from the M11 Template, "Allowable windows should be stated for all visits," to mean that an Encounter must be related to a Timing and that in that Timing, the timingWindowLower and timingWindowUpper attributes must be populated.
The text from the M11 template says a lot more than that.
I assume this rule is trying to define the rule Dave IH suggested, "If timing window present then Lower and Upper should be present".  That rule is broader than "Allowable windows should be stated for all visits,"  It says that if a Timing has timingWindow populated, then both the timingWindowLower and timingWindowUpper attributes must be populated.

**Comment by DianeWold** [comment]
This rule seems to be trying to deal with terminology for reasons.  It relates to DDF00009, which deals with conditional activities needing reasons.

**Comment by ASL-rmarshall** [comment]
@rbakercdisc1 
> @ASL-rmarshall We debated this in terms of how the timing should be differentiated in the logic. I am not sure of the answer.
> 
> In terms of the resource, I was trying to provide any reference found in M11 which as you state is not much. I felt compelled to show due diligence and point out what was included. Perhaps, it may be better to only show it if it is perfectly aligned and supported.
> 
> I agree with your statements. Do you have recommendations for the logic (include the encounterSheduleTiming)? There is an additional rule for the Timeline and ScheduledInstances.

I like the idea of Cited Guidance being specific - i.e., only include explicit references to the definition of the check. This makes review of the check definition easier because it's more targeted.  I think this aligns with the way SDTM checks are defined.

Based on the conversation we had in the daily meeting today, and also on Diane's comments above, I'd recommend splitting this into two visit-specific rules and one generic rule:
1. Every visit must have associated timing (i.e., every instance of the `Encounter` entity must have an `encounterScheduledAtTiming` relationship to an instance of the `Timing` entity).
2. Every visit timing must define a window (i.e., `timingWindow` must be populated in every instance of the `Timing` entity that is referenced by an `encounterScheduledAtTiming` relationship from an instance of the `Encounter` entity).
3. Timing windows must be fully defined (i.e., if any of `timingWindow`, `timingWindowLower` or `timingWindowUpper` is populated in an instance of the `Timing` entity, then all three must be populated).

(FYI @DianeWold)

**Comment by rbakercdisc1** [comment]
@ASL-rmarshall 

Can we move this to done?  

Also, did you request the other two rules you referenced?  Thanks.

**Comment by ASL-rmarshall** [comment]
@rbakercdisc1 @DianeWold Based on Dave IH's comments, it seems that M11's "Allowable windows should be stated for all visits"  specification is not applicable to USDM.  The "timing windows must be fully defined" part of the rule still holds true, but should we deprecate "Every visit must have associated timing" (#52) and "Every visit timing must have a window" (#53)?

**Comment by rbakercdisc1** [comment]
@ASL-rmarshall  @DianeWold 

I would wait to see how this evolves. USDM and M11 were going to eventually align.  It might be good to see how the feedback on Monday informs the direction of the work.
