### ISSUE TITLE
Define general rule DDF99993: For classes with next and previous relationships, the next and previous relationships must establish an ordered list of instances of the class.

### ISSUE THREAD

**Issue by DianeWold** [cdisc-org/ddf-core-poc#89]
CHK0040: This is a generalization of the rule that epochs must have a linear order - see #48.
The model may change in future so that eligibilty criteria are in two lists, one for inclusion criteria, one for exclusion criteria.

**Comment by DianeWold** [comment]
This rule is a generalization of DDF99997. 
Having trouble creating a new rule in the rule editor.  Intend to give it the number DDF99993.

**Comment by rbakercdisc1** [comment]
Review complete. The definition of done has been met.

**Comment by ASL-rmarshall** [comment]
Some of the check components for ordering (as specified in #48) can be applied generically, and some cannot.  For example, checking that any `id` value is used not more than once for `previousId` or `nextId` (within a `StudyDesign` instance) can be applied to any class with `previousId` and `nextId`. However, checking for valid `id` values cannot be generic because `nextId` and `previousId` in:
- `StudyEpoch` should only contain `StudyEpoch.id` values from within the same instance of `StudyDesign`.
- `Activity` should only contain `Activity.id` values from within the same instance of `StudyDesign`.
- `Encounter` should only contain `Encounter.id` values from within the same instance of `StudyDesign`.
- `EligibilityCriteria` should only contain `EligibilityCriteria.id` values from within the same instance of `StudyDesign` **and `category`**.

This means that it would probably be better to create separate rules for each ordering check component and, where necessary, type of instance.
